### ISSUE TITLE
[Question] Why main dispatcher?

### ISSUE THREAD

**Issue by troZee** [navi25/RetrofitKotlinDeferred#1]
Hello, 
Can you explain me something. 
I changed this line 
https://github.com/navi25/RetrofitKotlinDeferred/blob/master/app/src/main/java/io/navendra/retrofitkotlindeferred/ui/MainActivity.kt#L27
into 
`GlobalScope.launch(Dispatchers.Default) {`

And both solutions works. 

Why coroutine from Main Dispatcher did not return NetworkOnMainThreadException ? 
This network call is called from Main thread.

**Comment by navi25** [comment]
I haven't had a chance to go deep into understanding the inner workings of dispatchers but my wild guess is that Dispatcher is the one who handles the lifecycle of the Coroutines and related thread pool. But this is just my guess. This is not backed by any documentation or tech article. And hence Dispathcers.Main means that the main thread will be handling all the related coroutines lifecycle and resource. 
Also between which one to choose between IO/Main/Default, [I think this tweet from Chris Banes will be helpful.](https://twitter.com/chrisbanes/status/1085862292799901698?s=20)
![image](https://user-images.githubusercontent.com/10193839/53062404-f6578d00-347d-11e9-99c1-6fe0d923bb40.png)

And also checkout this documentation to understand more about these:
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/index.html
